services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
    ports:
      - "${PORT}:4000"
    volumes:
      - .:/app:delegated
      - /app/node_modules
    command: ["npm", "run", "dev"]
    restart: always

  migrate:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app:delegated
      - /app/node_modules
    command: ["npx", "prisma", "migrate", "deploy"]
    restart: "no"

  prisma-studio:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app:delegated
      - /app/node_modules
    ports:
      - "5555:5555"
    command: ["npx", "prisma", "studio"]

volumes:
  pgdata:
